### ISSUE TITLE
Map6的地图不显示

### ISSUE THREAD

**Issue by Princebin** [tianxiaofan/QtLocationTianditu#1]
demo可以获取到瓦片，但是好像不显示地图，你看看

**Comment by tianxiaofan** [comment]
修复了

**Comment by Princebin** [comment]
请问一下，db生成了，但是内容为空




Bennie&nbsp;Wu
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tianxiaofan/QtLocationTianditu"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 下午3:01
***@***.***&gt;;
抄送:&nbsp;"Bennie ***@***.******@***.***&gt;;
主题:&nbsp;Re: [tianxiaofan/QtLocationTianditu] Map6的地图不显示 (Issue #1)





 
修复了
