### ISSUE TITLE
数据库无法写入

### ISSUE THREAD

**Issue by Princebin** [tianxiaofan/QtLocationTianditu#2]
QMetaObject::invokeMethod(TiMapEngine::instance()->getSqlThread(), "readTile",
                              Qt::BlockingQueuedConnection, Q_ARG(QSharedPointer<TiMapTile>, tile));
    qDebug() << "read time:" << clock() - start << "ms";
占用了m_query，导致 if (!m_query || m_query->isActive() || m_queue.isEmpty())
        return;
所以数据库无法写入

**Comment by tianxiaofan** [comment]
这个数据库的读写逻辑存在问题的，晚上回去我重写一个

**Comment by Princebin** [comment]
加油，我认为如果在线就不用读数据库了

**Comment by tianxiaofan** [comment]
现重写地图插件，可稳定运行。#a469ad2b9c3f89ad51253786f079e765f4b54cc0
